/**
 *
 * @author Kraptukrait
 */
public class MainWindow extends javax.swing.JFrame {
    private String input = "";

    public MainWindow() {
        initComponents();
        this.textFieldOutput.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textFieldOutput = new javax.swing.JTextField();
        buttonInput7 = new javax.swing.JButton();
        buttonInput8 = new javax.swing.JButton();
        buttonInput9 = new javax.swing.JButton();
        buttonInput4 = new javax.swing.JButton();
        buttonInput5 = new javax.swing.JButton();
        buttonInput6 = new javax.swing.JButton();
        buttonInput1 = new javax.swing.JButton();
        buttonInput2 = new javax.swing.JButton();
        buttonInput3 = new javax.swing.JButton();
        buttonInputPlus = new javax.swing.JButton();
        buttonInputMinus = new javax.swing.JButton();
        buttonInputTimes = new javax.swing.JButton();
        buttonInputDivide = new javax.swing.JButton();
        buttonInputEqual = new javax.swing.JButton();
        buttonInputClear = new javax.swing.JButton();
        buttonInput0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Calculator");

        textFieldOutput.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        buttonInput7.setText("7");
        buttonInput7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7(evt);
            }
        });

        buttonInput8.setText("8");
        buttonInput8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8(evt);
            }
        });

        buttonInput9.setText("9");
        buttonInput9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9(evt);
            }
        });

        buttonInput4.setText("4");
        buttonInput4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4(evt);
            }
        });

        buttonInput5.setText("5");
        buttonInput5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5(evt);
            }
        });

        buttonInput6.setText("6");
        buttonInput6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6(evt);
            }
        });

        buttonInput1.setText("1");
        buttonInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1(evt);
            }
        });

        buttonInput2.setText("2");
        buttonInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2(evt);
            }
        });

        buttonInput3.setText("3");
        buttonInput3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3(evt);
            }
        });

        buttonInputPlus.setText("+");
        buttonInputPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlus(evt);
            }
        });

        buttonInputMinus.setText("-");
        buttonInputMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinus(evt);
            }
        });

        buttonInputTimes.setText("X");
        buttonInputTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTimes(evt);
            }
        });

        buttonInputDivide.setText("/");
        buttonInputDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivide(evt);
            }
        });

        buttonInputEqual.setText("=");
        buttonInputEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqual(evt);
            }
        });

        buttonInputClear.setText("C");
        buttonInputClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonC(evt);
            }
        });

        buttonInput0.setText("0");
        buttonInput0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonInput7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonInput8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonInput9))
                    .addComponent(textFieldOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonInput4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonInput5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonInput6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonInput1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonInput2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonInput3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonInputPlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonInputMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonInputTimes))
                    .addComponent(buttonInputDivide)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonInputEqual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonInputClear))
                    .addComponent(buttonInput0))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInput7)
                    .addComponent(buttonInput8)
                    .addComponent(buttonInput9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInput4)
                    .addComponent(buttonInput5)
                    .addComponent(buttonInput6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInput1)
                    .addComponent(buttonInput2)
                    .addComponent(buttonInput3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(buttonInput0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInputPlus)
                    .addComponent(buttonInputMinus)
                    .addComponent(buttonInputTimes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonInputDivide)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInputEqual)
                    .addComponent(buttonInputClear))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>                        

    private void button1(java.awt.event.ActionEvent evt) {                         
        input = input + "1";
        this.textFieldOutput.setText(input);
    }                        

    private void button2(java.awt.event.ActionEvent evt) {                         
        input = input + "2";
        this.textFieldOutput.setText(input);
    }                        

    private void button3(java.awt.event.ActionEvent evt) {                         
        input = input + "3";
        this.textFieldOutput.setText(input);
    }                        

    private void button4(java.awt.event.ActionEvent evt) {                         
        input = input + "4";
        this.textFieldOutput.setText(input);
    }                        

    private void button5(java.awt.event.ActionEvent evt) {                         
        input = input + "5";
        this.textFieldOutput.setText(input);
    }                        

    private void button6(java.awt.event.ActionEvent evt) {                         
        input = input + "6";
        this.textFieldOutput.setText(input);
    }                        

    private void button7(java.awt.event.ActionEvent evt) {                         
        input = input + "7";
        this.textFieldOutput.setText(input);
    }                        

    private void button8(java.awt.event.ActionEvent evt) {                         
        input = input + "8";
        this.textFieldOutput.setText(input);
    }                        

    private void button9(java.awt.event.ActionEvent evt) {                         
        input = input + "9";
        this.textFieldOutput.setText(input);
    }                        

    private void buttonC(java.awt.event.ActionEvent evt) {                         
        input = "";
        this.textFieldOutput.setText(input);
    }                        

    private void buttonPlus(java.awt.event.ActionEvent evt) {                            
        input = input + "+";
        this.textFieldOutput.setText(input);
    }                           

    private void buttonMinus(java.awt.event.ActionEvent evt) {                             
        input = input + "-";
        this.textFieldOutput.setText(input);
    }                            

    private void buttonTimes(java.awt.event.ActionEvent evt) {                             
        input = input + "*";
        this.textFieldOutput.setText(input);
    }                            

    private void buttonDivide(java.awt.event.ActionEvent evt) {                              
        input = input + "/";
        this.textFieldOutput.setText(input);
    }                             

    private void buttonEqual(java.awt.event.ActionEvent evt) {                             
        Compute myCompute = new Compute(input);
        this.input = input + "=" + myCompute.getResult();
        this.textFieldOutput.setText(input);
        double result = myCompute.getResult();
        input = String.valueOf(result);
    }                            

    private void button0(java.awt.event.ActionEvent evt) {                         
        input = input + "0";
        this.textFieldOutput.setText(input);
    }                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonInput0;
    private javax.swing.JButton buttonInput1;
    private javax.swing.JButton buttonInput2;
    private javax.swing.JButton buttonInput3;
    private javax.swing.JButton buttonInput4;
    private javax.swing.JButton buttonInput5;
    private javax.swing.JButton buttonInput6;
    private javax.swing.JButton buttonInput7;
    private javax.swing.JButton buttonInput8;
    private javax.swing.JButton buttonInput9;
    private javax.swing.JButton buttonInputClear;
    private javax.swing.JButton buttonInputDivide;
    private javax.swing.JButton buttonInputEqual;
    private javax.swing.JButton buttonInputMinus;
    private javax.swing.JButton buttonInputPlus;
    private javax.swing.JButton buttonInputTimes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField textFieldOutput;
    // End of variables declaration                   
}
